import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal.family = "DaddyTimeMono Nerd Font"
bold.family = "DaddyTimeMono Nerd Font"
italic.family = "DaddyTimeMono Nerd Font"
bold_italic.family = "DaddyTimeMono Nerd Font"

size = 16.0

[env]
TERM = "xterm-256color"

